name: Benchmark tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.6.1

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      # Run benchmark
      - name: Run benchmark
        run: |
          python benchmark.py
          python write_json_data.py ${{ github.workspace }}/outputs/benchmark_result.json ${{ github.workspace }}/benchmark_records/new_record.json
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/benchmark_cache
          key: benchmark_data
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'customSmallerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: ${{ github.workspace }}/benchmark_records/new_record.json
          # Where the previous data file is stored
          external-data-json-path: ${{ github.workspace }}/benchmark_cache/benchmark_data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
      # Upload the updated cache file for the next job by actions/cache