name: Benchmark tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  # deployments permission to GH-pages site
  deployments: write
  # contents permission to update GH-pages content
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.6.1

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      # Run benchmark
      - name: Run benchmark
        run: |
          python benchmark.py
          python write_json_data.py ${{ github.workspace }}/outputs/benchmark_result.json ${{ github.workspace }}/benchmark_records/new_record.json
      # Download previous benchmark result from cache (if exists)
      # - name: Download previous benchmark data
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ github.workspace }}/benchmark_cache
      #     key: benchmark_data
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'customSmallerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: ${{ github.workspace }}/benchmark_records/new_record.json
          # Access token to deploy to GH-pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # gh-pages branch name
          gh-pages-branch: gh-pages
          # directory on gh-pages branch to place benchmark dashboard page
          benchmark-data-dir-path: ./
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # Push and deploy automatically
          auto-push: true
      # Upload the updated cache file for the next job by actions/cache