name: Job dependency experiments
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  job-1:
    name: Run on dispatch
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "Ran the dispatch job"
  
  job-2:
    name: Run on pull requests against main
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - run: echo "Ran the push job"

  dependent-job:
    name: Only if one of the two earlier jobs ran
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    if: |
      always() &&
      (needs.job-1.result == 'success' || needs.job-1.result == 'skipped') &&
      (needs.job-2.result == 'skipped' || needs.job-2.result == 'success') &&
      !(needs.job-1.result == 'skipped' && needs.job-2.result == 'skipped')
    steps:
      - run: echo "Ran the dependent job"
